spring.datasource.url= jdbc:mysql://${mysql.local.host}/${mysql.local.database}?createDatabaseIfNotExist=true&sslMode=PREFERRED&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=truespring.datasource.driverClassName= org.h2.Driver
spring.datasource.username= ${mysql.local.username}
spring.datasource.password= ${mysql.local.password}
spring.sql.init.platform= h2
spring.jpa.database-platform= org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto= update

azure.backend.url= https://bandd-se-2025-dqe3g7ewf8b7gccf.northeurope-01.azurewebsites.net


# Disable security
spring.security.filter.disabled=true

# Disable Actuator security
management.security.enabled=false

## MULTIPART (MultipartProperties)
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

# Actuator
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.loggers.enabled=true
management.endpoint.beans.enabled=true
management.endpoint.shutdown.enabled=true
management.endpoint.startup.enabled=true
management.endpoint.threaddump.enabled=true
management.endpoint.heapdump.enabled=true
# http://localhost:8080/actuator/env/spring.profiles.active
management.endpoint.env.enabled=true
management.endpoints.web.exposure.include=health,loxggers,beans,env,shutdown,startup,threaddump,heapdump
management.security.user.name=actuator
management.security.user.password=monitor

# Main application security
spring.security.user.name=postman
spring.security.user.password=access123
spring.security.user.roles=USER
# Loggers
logging.level.root=INFO
logging.level.pw.react.backend=INFO
logging.level.org.springframework.boot.autoconfigure=ERROR

# CORS
cors.urls=${cors:http://localhost:8080,http://localhost:8081,http://10.0.2.2:8081,http://localhost:5000,http://localhost:8000,http://127.0.0.1:8000,https://bandd-se-2025-dqe3g7ewf8b7gccf.northeurope-01.azurewebsites.net}
cors.mappings=/**

# stripe
stripe.secret-key=${stripe.secret_key}
stripe.webhook-secret=${stripe.webhook_secret}

# spring-doc
application.springdoc.title=Backend PW API
application.springdoc.description=Backend starter for PW project.
application.springdoc.version=@project.version@
springdoc.show-actuator=true
#springdoc.swagger-ui.path=/swagger-ui-custom.html
#springdoc.swagger-ui.operationsSorter=method


# http://localhost:8080/swagger-ui.html
# JSON based API-docs - http://localhost:8080/v3/api-docs.
# For YAML based API-docs use  http://localhost:8080/v3/api-docs.yaml