management.endpoints.web.cors.allowed-origins=${cors_origins:http://localhost:8080,http://localhost:5000,http://localhost:8000,http://localhost:8081,http://127.0.0.1:8000,http://10.0.2.2:8081,https://bandd-se-2025-dqe3g7ewf8b7gccf.northeurope-01.azurewebsites.net}
management.endpoints.web.cors.allowed-headers=${cors_headers:*}
management.endpoints.web.cors.allowed-methods=${cors_methods:*}
management.endpoints.web.cors.allowed-origin-patterns=${cors_origin_patterns:/**}