# Generated by Django 5.2.9 on 2025-12-15 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAndDock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='tips',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='BookAndDock.comment'),
        ),
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('guide', 'Guide'), ('article', 'Article')], default='guide', max_length=10),
        ),
        migrations.AddField(
            model_name='guide',
            name='external_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='guide',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('to_be_accepted', 'Accept')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='docks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DockSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField(help_text='Length of the dock space (in meters)')),
                ('width', models.FloatField(help_text='Width of the dock space (in meters)')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='BookAndDock.dock')),
            ],
        ),
    ]
